### ISSUE TITLE
Add GUI based Hangman Game

### ISSUE THREAD

**Issue by whynaidu** [cmulay/python-aio#20]
**Is your feature request related to a problem? Please describe.**
This repository already contains the game hangman but it's a CLI based game.

**Describe the solution you'd like**
A Game Called Hangman With an Interactive GUI

**Comment by cmulay** [comment]
That would be a great addition we have CLI based hangman. 
Please go ahead with this contribution !

**Comment by cmulay** [comment]
@whynaidu any updates ?
