### ISSUE TITLE
Restructure the project

### ISSUE THREAD

**Issue by cmulay** [cmulay/python-aio#21]
Create proper project structure and navigational / contribution guide

**Comment by mani-barathi** [comment]
@cmulay  Do You have any idea how to structure the project?
Let me know I'll see if I can do that

**Comment by cmulay** [comment]
I have not thought about it what is your approach ?

**Comment by mani-barathi** [comment]
For Now, I think we can start categorizing  projects based whether its is **CLI** based or **GUI** based .

And then provide a navigation tree kinda of thing in README so that people know what are all the projects comes under the categories.

**Comment by cmulay** [comment]
That would be great ! Can you go ahead with these changes ?

**Comment by mani-barathi** [comment]
Yeah

**Comment by mani-barathi** [comment]
@cmulay I'll also add a folder called **Games**, as we have quite a few games in the repo.

**Comment by cmulay** [comment]
Can also create a folder for python **Scripts** ?

**Comment by mani-barathi** [comment]
@cmulay  **Right Now it looks like this**
|─── **CLI**
│   ├───Addressbook
│   ├───Advance Email Slicer
│   ├─── ...._Many More_
├─── **Games**
│   ├───Guess the Number
│   ├───Hangman
│   ├─── ...._Many More_
 |─── **GUI**
│   ├───Alarm Clock
│   ├───Currency Converter
│   ├─── ...._Many More_

**Comment by cmulay** [comment]
Looks good to me !

**Comment by mani-barathi** [comment]
@cmulay Should I add a **Beginner** category as some projects/programs are very beginner-friendly?

**Comment by cmulay** [comment]
Yeah sure !

**Comment by cmulay** [comment]
Thank you so much @mani-barathi for doing the restructuring of the project !

**Comment by mani-barathi** [comment]
> Thank you so much @mani-barathi for doing the restructuring of the project ! 

Happy to contribute!
