### ISSUE TITLE
Is venv really required?

### ISSUE THREAD

**Issue by mani-barathi** [cmulay/python-aio#25]
### Problem
**venv** folder in the root directory is increasing the size of the repo.
Imagine the situation where a person clone's the repo for downloading a couple of projects, but because of the `venv ` folder, they should download more than **100Mb** which is not nice. 
And in most cases, people cloning the repo will have their own python installation on their computer

@cmulay what's your thought on this?

**Comment by cmulay** [comment]
thanks for bringing it to my attention. adding venv to .gitignore will solve this issue.

**Comment by mani-barathi** [comment]
Will you fix this or should I fix and make a PR

**Comment by cmulay** [comment]
I'll add it, thanks

**Comment by cmulay** [comment]
Hey @mani-barathi ,
I've added venv to .gitignore and to .gitexclude as well yet it doesn't seem to work. Can you have a look into it ?

**Comment by mani-barathi** [comment]
@cmulay I'll look into this

**Comment by cmulay** [comment]
Yes, thank you !
