### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by kaar07** [cmulay/python-aio#27]
### Repo is missing CONTRIBUTING.md and Code of Conduct 
Although they are mentioned in README.md of cmulay/python-io, files are missing.   
Do the necessary as required and in convenience.  

These could ease the process:
- [Adding default community health files - github](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)
- [github/docs CONTRIBUTING.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md)
- [How to build a CONTRIBUTING.md - mozilla science lab](https://mozillascience.github.io/working-open-workshop/contributing/)

Regards,  
Kaarthik.

**Comment by cmulay** [comment]
Thankyou @kaar07, I will surely add these as soon as I can !

**Comment by cmulay** [comment]
Added Contributing.md
