### ISSUE TITLE
I want to contribute my Personal Assistant python project to your repository

### ISSUE THREAD

**Issue by Deepkk-9** [cmulay/python-aio#33]
I have made a Personal Assistant in python. 
This is version 1, will work continuously on this. 

- Features, added till now:
1. Can open all the basic desktop apps.
2. You can also listen to music 
3. Basic web-based activities like GitHub, Wikipedia and YouTube.

**Comment by cmulay** [comment]
@Deepkk-9 Go ahead 👍🏻

**Comment by cmulay** [comment]
No progress
